### ISSUE TITLE
Issue with requireJS

### ISSUE THREAD

**Issue by Nadoedalo** [w8tcha/CKEditor-AutoSave-Plugin#102]
So I've encountered this issue of silent errors while loading the page with CKEditor and found out that it is actually a plugin that breaks it.

It is 2018 on the playground, everything should be require-js friendly.
So the issue is that after CKEditor builds a package into minified version your plugin sometimes just breaks everything(and sometimes everything works well, and there is no errors to catch it because requireJS for some reason does it silently).

I've come up with a quick fix - DON'T use amd define.
So basically I've switched 
https://github.com/w8tcha/CKEditor-AutoSave-Plugin/blob/master/autosave/js/moment.js
```javascript
;(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
    typeof define === 'function' && define.amd ? define(factory) :
    global.moment = factory()
}(this, (function () { 'use strict';
//nice ; you have there
```
to
```javascript
;(function (global, factory) {
    global.moment = factory()
}(this, (function () { 'use strict';
```
and 
https://github.com/w8tcha/CKEditor-AutoSave-Plugin/blob/master/autosave/js/lz-string.js
```javascript
//from line 497
if (typeof define === 'function' && define.amd) {
  define(function () { return LZString; });
} else if( typeof module !== 'undefined' && module != null ) {
  module.exports = LZString
}
```
to
```javascript
//none. Basically deleted everything.
```

Please issue a quick fix(everything seems to be working fine) or come up with a better idea. I see no harm in deleting amd-support while everything else if working.
PS I saw a similar issue and a tag 'wontfix'. Is there any reasoning behind that decision?

**Comment by w8tcha** [comment]
Feel free to send in a pull request. The problem i do not use require,js and i never will. And i have no idea how to solve issues like this. And my questions in the past to post sample content with a ckeditor including requirejs so i can reproduce the issue and test it. Have not been answered. So without help the only thing i can do is add the label wontfix

**Comment by Nadoedalo** [comment]
OK I will try to create a simple example of an error and send in the pull request with quick fix on the weekend.

**Comment by Nadoedalo** [comment]
Created a pull request 
https://github.com/w8tcha/CKEditor-AutoSave-Plugin/pull/103

Sorry for taking that long. I haven't got any working examples but removing AMD modules definition helped to solve the issue.

**Comment by w8tcha** [comment]
Thanks its really not a fix instead its a workaround, but since you didn't provide a sample page  i merge the workaround
