### ISSUE TITLE
Issues with the CKEditor plugin AutoSave, when there is more than one editor on the same page

### ISSUE THREAD

**Issue by KenHaynes** [w8tcha/CKEditor-AutoSave-Plugin#108]
I have a web page which contains 6 CKEditor instances, using the AutoSave plugin.

The AutoSave plugin works perfectly with single instances on a page but not with multiple instances. Multiple instances cause erratic behavior in that 6 prompts relating to autosaved content are displayed one at a time, but they are unresponsive.

I appreciate that each CKEditor instance requires a unique ID (as is illustrated in the code below) and research has shown me how to set these IDs within CKEditor.replace but for the life of me, I cannot get it to work.

I have tried different browsers and cache cleaning, to no avail.

The following code is in a loop of 6 iterations within a table. I have verified that the ColdFusion variable values are correct. The autosave_Savekey range is "autosave_2" to "autosave_7".

```
<td>
<textarea name="text_value_box#agi_array[agi][5]#" cols="78" rows="<cfif #agi_array[agi][4]# EQ "R">4<cfelse>8</cfif>" #route_form#>#getItem.text_value#</textarea>
<script type="text/javascript">
    CKEDITOR.replace( 'text_value_box#agi_array[agi][5]#',
     {
        customConfig: '#Editor.customConfig#',
        allowedContent: true,
        autosave_SaveKey: 'autosave_#agi_array[agi][5]#',
        toolbar: '#Editor.toolbar#'
        <cfif isDefined('Editor.font_names')>
        , font_names: '#Editor.font_names#'
        </cfif>
        <cfif isDefined('Editor.fontSize_sizes')>
        , fontSize_sizes: '#Editor.fontSize_sizes#'
        </cfif>
        <cfif not vIsSuperUser>
        , removePlugins: 'elementspath'
        </cfif>
     }
    );
</script>
</td>
```
Is this a know issue? I would be grateful for any suggestions as to a resolution.

Tech Spec: CKEditor version: 4.9.2. AutoSave Version: 0.1.8. ColdFusion Version: 11. Browsers Tested: Firefox, IE and Chrome.

**Comment by w8tcha** [comment]
the config setting is wrong it should be

```
CKEDITOR.replace( 'text_value_box#agi_array[agi][5]#', {
	autosave:
                    {
                        SaveKey: 'autosave_#agi_array[agi][5]#'
                    }
	... some other configurations omitted here
});
```

**Comment by KenHaynes** [comment]
Thank you so much w8tcha, that worked perfectly.
