### ISSUE TITLE
messageType: 'statusbar' depends on wordcount plugin

### ISSUE THREAD

**Issue by nmpetkov** [w8tcha/CKEditor-AutoSave-Plugin#109]
In plugin.js there are two fragments like this:
```
if (editor.plugins.wordcount && config.messageType == "statusbar") {
    config.messageType = "notification";
}
```
which I comment to prevent this dependency.
Autosave message appear in the centre of the status bar, so there is no conflict with wordcount plugin information.

**Comment by w8tcha** [comment]
That not a dependency! It just checks that if the wordcount plugin is used it prevents the use of the statusbar

**Comment by nmpetkov** [comment]
Why not? Messages coexist well together.

**Comment by w8tcha** [comment]
No it does not work together see the screen shot in issue  #60

**Comment by nmpetkov** [comment]
In my case they work well together, as seen from screenshot below.
If the user uses wordcount, and do not like autosave message to be placed in status bar, then why will put setting ``messageType: 'statusbar' ```` ?

![image](https://user-images.githubusercontent.com/628801/42419227-029e456c-82b9-11e8-937a-6c0285ad856a.png)

**Comment by nmpetkov** [comment]
Ok, thanks, will comment this two code fragments.
