### ISSUE TITLE
AutoSave Config Modifications Not Working

### ISSUE THREAD

**Issue by smbcreativegroup** [w8tcha/CKEditor-AutoSave-Plugin#111]
I have installed the latest version of AutoSave Plugin and have modified the config.js file as you can see here: https://www.screencast.com/t/c60BXtI8xkh

However, the changes are not taking effect in my editor.

The message is still popping up instead of showing a message in the status bar as you can see here: https://www.screencast.com/t/7WfecTfwgx

I have cleared DNN host cache, browser cache, stopped and started the website in IIS and also recycled app pool.

Can you please tell me what I may be doing wrong for these new Auto Save settings to take effect?

Thank you.

**Comment by w8tcha** [comment]
Modifying the config.js is useless it its not used by the editor. All you need is open the editor options and under the config tab change the autosave setting directly (AutoSave - MessageType).

**Comment by smbcreativegroup** [comment]
If the config.js file is not where the settings are changed, then what is this page referencing: https://github.com/w8tcha/CKEditor-AutoSave-Plugin

**Comment by smbcreativegroup** [comment]
Where do I change it on the Config Tab? https://www.screencast.com/t/ji64Aa4QNq1u

**Comment by w8tcha** [comment]
<img width="592" alt="autosave" src="https://user-images.githubusercontent.com/722575/48082157-1b3b3380-e1f2-11e8-81c2-3609336aee25.PNG">

all autosave settings are on the editor config tab

**Comment by smbcreativegroup** [comment]
My config editor is not showing these options.  What do i need to do in order for them to display?

**Comment by w8tcha** [comment]
It should appear in the editor config if you're using the latest version. Which dnn version are you using?

**Comment by smbcreativegroup** [comment]
7.4

**Comment by smbcreativegroup** [comment]
Sorry to bother, but do you have any suggestions on what i can look for to resolve this issue?  I have confirmed that I installed your latest version of your plugin: see here: https://www.screencast.com/t/rlSUWBsYY

And i've installed the latest version of your DNN CKeditor: https://www.screencast.com/t/lbKfQKp6ADf1

I'm running DNN 7.4.1

We are kind of in a bind, because the popup is hovering over an area of a module where its causing problems.

Thank you as always for your help.

**Comment by w8tcha** [comment]
[WatchersNET.CKEditor.zip](https://github.com/w8tcha/CKEditor-AutoSave-Plugin/files/2563352/WatchersNET.CKEditor.zip)

my only guess is that the installation of the latest provider was not succesfull. I tested the dnn 7 package and it shows the correct settings.

i attached the dll. What happens when you put the dll in the bin folder of your dnn installation?

**Comment by smbcreativegroup** [comment]
This appears to have fixed it.  The fields are now there.  Thank you.  I noticed these fields don't have a description of each setting when I mouse over the new settings.  Do you have a list of those anywhere?

**Comment by smbcreativegroup** [comment]
2 things I am noticing.  

1. The Delay time is not saving when I alter the Editor Config.
2. I have the message display set to "statusbar" and it is still showing in the middle of the screen. 
see video: https://www.screencast.com/t/lH0grsGo

**Comment by smbcreativegroup** [comment]
Thank you very much.  I have tested this and is working.  One note, the version # in the build you gave me still had the old version number in the release notes.You need to update it to 2.01.18.  Thank you again.

**Comment by w8tcha** [comment]
I updated the downloads, with the correct version number
