### ISSUE TITLE
Bug with big words

### ISSUE THREAD

**Issue by groseler** [w8tcha/CKEditor-AutoSave-Plugin#115]
Hi! Thank you for this awesome plugin. I just found a small bug, you should include in css in the tags `table.diff tbody td {word-break: break-word;}`
Big words as images base64 can break the layout. Check the image below.

![Screenshot 2019-06-12 at 10 53 34](https://user-images.githubusercontent.com/25203062/59341949-bd7b4680-8d00-11e9-80cd-3ff9a5baeefd.png)

Cheers!

**Comment by w8tcha** [comment]
Thanks fixed!
