### ISSUE TITLE
Diff window problem

### ISSUE THREAD

**Issue by groseler** [w8tcha/CKEditor-AutoSave-Plugin#116]
Hi!
I'm having a problem. The Diff window opens and closes instantly, unless I have the chrome dev tools open with **disabled cache checked**. Do you know anything about this behaviour?

**Comment by w8tcha** [comment]
No i don't. Did you get any Java script errors? Which Editor version did you use? Can you provide some sample files. so i can try to reproduce the issue?

**Comment by groseler** [comment]
No js errors, just the diff warning flashing. What kind of sample files?

**Comment by w8tcha** [comment]
and which version 4? the latest 4.12.1? With sample files i mean the editor config you are using.

**Comment by groseler** [comment]
CKEditor 4.9.2. I will try to update it, check the results. If the problem persists I will let you know.
