### ISSUE TITLE
Possible to create more recent tag?

### ISSUE THREAD

**Issue by jonespm** [w8tcha/CKEditor-AutoSave-Plugin#119]
Hi, love this project!

Would it be possible to create a more recent tag on this project? From what I can tell the last tag was v0.18.1 which was created almost 2 years ago in 2017. I normally wouldn't ask and use master however we are using your plugins from Webjars which currently is based on a versioned tag and would need that to easily update. We *could* change those to update off a SHA in master but figured I'd check first.  

https://github.com/webjars/ckeditor-autosave

This is same for Wordcount
https://github.com/webjars/ckeditor-wordcount

Because semver can be difficult sometimes to keep up with it'd even be fine if you just switched to a [calver](https://calver.org/) tag and had it something like 2019.01 (YYYY.MINOR) or 2019.10.25 (YYYY.MM.DD) just so we have some tag.

Thanks again!

**Comment by w8tcha** [comment]
i assume you mean the version tag in the package.json?

**Comment by jonespm** [comment]
I mostly meant a new tag/release in Github, but updating the package.json would probably be appropriate (and maybe needed) to.

**Comment by w8tcha** [comment]
done

**Comment by jonespm** [comment]
Awesome, thanks!
