### ISSUE TITLE
Editor without ID attribute

### ISSUE THREAD

**Issue by sirdemoncze** [w8tcha/CKEditor-AutoSave-Plugin#120]
Hi,

firstly thanks for you plugin ;-).

In my project i use **only NAME attribute** as selector for CKEDITOR. No ID attribute. 

After load your plugin i get error on **row 42**:
`SaveKey: _saveKeyPrefix + _saveKeyDelimiter + _saveKeyUrl + _saveKeyDelimiter + document.getElementById(editor.name).getAttribute(_saveKeyAttribute),`

My temporary solution is **replace row in source code**: 
`SaveKey: _saveKeyPrefix + _saveKeyDelimiter + _saveKeyUrl + _saveKeyDelimiter + editor[_saveKeyAttribute],`

Do you have any idea, how can i write this **SaveKey** into CKEDITOR config without edit your source code?

**Comment by w8tcha** [comment]
You can set this setting in you editor config

**Comment by sirdemoncze** [comment]
Sorry, but is not possible, because CKEDITOR config is extend **on row 48** (6 rows later). 

This code generate error during init, if element has not ID attribute. 
`document.getElementById(editor.name)`

**Comment by w8tcha** [comment]
I dont undertand the problem you can set the setting in the config to whatever string you want.

for example
CKEDITOR.replace('editor1',
                {
                    extraPlugins: 'autosave',
                    autosave:
                    {
                        SaveKey: "yoursavekey"

                    }
                });

**Comment by sirdemoncze** [comment]
After use your code i get this error bellow:
![Snímek obrazovky 2020-04-15 v 12 42 25](https://user-images.githubusercontent.com/32384277/79328958-36e25780-7f17-11ea-8d7c-a806d76f9e2c.png)

Exactly here:
```            
// Construct default configuration
var defaultConfig = {
    delay: 10,
    messageType: "notification",
    saveDetectionSelectors: "a[href^='javascript:__doPostBack'][id*='Save'],a[id*='Cancel']",
    saveOnDestroy: false,
    NotOlderThen: 1440,
    SaveKey: _saveKeyPrefix + _saveKeyDelimiter + _saveKeyUrl + _saveKeyDelimiter + document.getElementById(editor.name).getAttribute(_saveKeyAttribute),
    diffType: "sideBySide",
    autoLoad: false
};

// Extend CKEDITOR config and lang  - config also available at loadPlugin()
var config = CKEDITOR.tools.extend(defaultConfig, editor.config.autosave || {}, true);
```  

As you see, extend **defaultConfig** by **editor.config.autosave** is **after inititialization defaultConfig**, but in defaultConfig is function **getElementById**, which generate error if element cannot has ID attribute.

**Comment by w8tcha** [comment]
No i understand the problem. I re-factored the code now the save key is handled after the config is parsed.

**Comment by sirdemoncze** [comment]
Thank you ;-)
