### ISSUE TITLE
autosave_saveDetectionSelectors not working for me

### ISSUE THREAD

**Issue by thanhansoft** [w8tcha/CKEditor-AutoSave-Plugin#122]
Hi,
I have a input type="submit" but not working.
It doesn't need to be stored temporary
config.autosave_saveDetectionSelectors = "input[type='submit']";

Please help me

**Comment by w8tcha** [comment]
that can not work! you need to setup the config like

`config.autosave = { saveDetectionSelectors : "input[type='submit']"};`

**Comment by thanhansoft** [comment]
okie, thanks you, it's working
