### ISSUE TITLE
Unable to save MathType

### ISSUE THREAD

**Issue by subodhk01** [w8tcha/CKEditor-AutoSave-Plugin#130]
Plugin is unable to save anything we write in the editor through Mathtype

**Comment by w8tcha** [comment]
Can you describe the steps to reproduce the problem? Also which editor version are you using?

**Comment by subodhk01** [comment]
I'm using django-ckeditor==5.9.0

*Steps to Reproduce:* 
Write anything on the editor with MathType input box, refresh the page and all your Mathtype data will be gone
<img width="601" alt="Screenshot 2020-09-27 at 13 12 40" src="https://user-images.githubusercontent.com/19875783/94359181-212aae00-00c3-11eb-8acd-70c41b179d38.png">

**Comment by w8tcha** [comment]
I commited an updated plugin. it should work now
