### ISSUE TITLE
Auto-removing storage when option autoLoad=true

### ISSUE THREAD

**Issue by leonid-ilin** [w8tcha/CKEditor-AutoSave-Plugin#131]
Hello,

I am facing the following problem. If I set the option "**autoLoad = true**" and, for example, set the option value "**delay = 10**", then after loading the content, it is automatically deleted, but if we refresh the page during these 10 seconds of delay, we have losed content at all

Problem [in this code](https://github.com/w8tcha/CKEditor-AutoSave-Plugin/blob/v0.18.5/autosave/plugin.js#L259):
```
if (config.autoLoad) {
    if (localStorage.getItem(autoSaveKey)) {
        var jsonSavedContent = LoadData(autoSaveKey);
        editorInstance.setData(jsonSavedContent.data);
        RemoveStorage(autoSaveKey, editorInstance);
    }
}
```

Maybe it makes sense move the "clearAfterAutoLoad" or something like this option into config?

**Comment by w8tcha** [comment]
This is the normal behavior, this has nothing to do with autoload set to true. You would need to decrease the delay to avoid it

**Comment by leonid-ilin** [comment]
I need to notify the user in the status bar (**messageType: "statusbar"**) that the content has been saved. If I, for example, set "**delay: 1**", then the notification will be displayed constantly while it changes the content.

But, even if you just turn off the notification (**messageType: "no"**), clearing the localstorage after downloading the content, and then immediately write it back looks like an unnecessary operation. Also if we talk about the **delay**, I would like to have some delay between saving content, but not before first saving.

**Comment by w8tcha** [comment]
I really dont understand the problem, why would you want to refresh the page immediately  after it was loaded?

**Comment by w8tcha** [comment]
If it helps maybe an option not to remove the saved data after it was loaded would help?!

**Comment by leonid-ilin** [comment]
> I really dont understand the problem, why would you want to refresh the page immediately after it was loaded?

It's not me, it's users :) I have panel-menu and users can click between sections faster than value of **delay** - from this there may be cases with missing content:

![image](https://user-images.githubusercontent.com/22326935/103256297-4cbd7d00-49bf-11eb-8cef-dff54494d42f.png)

> If it helps maybe an option not to remove the saved data after it was loaded would help?!

Yes, it will be great!
