### ISSUE TITLE
AutoSave saves not everytime

### ISSUE THREAD

**Issue by Famaxis** [w8tcha/CKEditor-AutoSave-Plugin#132]
I setup delay in config as '1', but the problem is still there.

When user quickly refreshes the page ten times in a row, or closes and opens his browser ten times, or clicking the other links, returns back to text and clicks somewhere again — text must be saved. He can do this, because he wants to be sure, that when he will type a long text, nothing in the world can remove the results of his work. Until he presses the button "publish". 

I mean something like garlic.js — https://github.com/guillaumepotier/Garlic.js, but it's not working with CKEditor.

**Comment by w8tcha** [comment]
Sorry but this doesnt make any sense. If you type a long text of course the text is saves. but how could you write something and hit the the refresh button 10 times at the same time. I only was able to hit one key.

Sorry but i cant help you with that problem

**Comment by Famaxis** [comment]
Yes, there is no practical sense, but it's good for user expirience and user's confidence in data safekeeping. Anyway, thanks for the answer.

**Comment by w8tcha** [comment]
Sorry for the late answer but you can remove the delay and set it to 0 and also disable notifications.

Then it saves directly.

**Comment by Famaxis** [comment]
Yes, it worked. Thanks! I love this plugin and gave a star.
