### ISSUE TITLE
Autosave message position

### ISSUE THREAD

**Issue by oleteacher** [w8tcha/CKEditor-AutoSave-Plugin#138]
Hello Friend!

Your plugin is working great.

When the autosave message appears, it is sometimes way to screen left and cutoff. Other times it is appearing in center but can barely see the message.

Where can I adjust these settings?

I have explored plugin.js but do see and obvious settings. Did notice requires for notification plugin.

Thanks!

**Comment by w8tcha** [comment]
Notifications are displayed via the notification plugin. According to the [Documentation](https://ckeditor.com/docs/ckeditor4/latest/features/notifications.html) the position can not be changed. 

But you could change the notification to be shown in the status bar 

`messageType : "statusbar`

**Comment by oleteacher** [comment]
Thank you @w8tcha for tip. You get me on the right track.

In my case using an older skin and did not have the notification.css. Simple fix for older skins:

https://ckeditor.com/docs/ckeditor4/latest/guide/skin_sdk_compatibility_with_ckeditor_4_5.html

Thanks again!
