### ISSUE TITLE
escape implementation issue

### ISSUE THREAD

**Issue by kuakkgom** [w8tcha/CKEditor-AutoSave-Plugin#39]
With current implementation of escape in extensions.js, there is an issue if a number is passed.  This breaks functionality in some pre-existing JavaScript that makes use of the native escape function.  In at least Chrome 41 the following occurs:

native escape: escape(2) -> "2"
extensions escape: escape(2) -> Uncaught TypeError: undefined is not a function.

A simple fix would be:
```
function escape(a)
{
    var b = a.toString();
    b = b.replace(/&/g, "&amp;");
    b = b.replace(/</g, "&lt;");
    b = b.replace(/>/g, "&gt;");
    b = b.replace(/"/g, "&quot;");
    return b
}
```
A better fix would be to have escape only scoped to your plugin as this implementation does not follow spec: (ECMAScript Spec - escape implementation)[http://www.ecma-international.org/ecma-262/5.1/#sec-B.2.1]

**Comment by magus424** [comment]
Or call it something like `escapeHTML` since it isn't performing the same task as `escape` :)

**Comment by kuakkgom** [comment]
Never mind, apparently that is fixed in a newer version.
