### ISSUE TITLE
autosaved data is not reloaded when page is opened

### ISSUE THREAD

**Issue by bramtassyns** [w8tcha/CKEditor-AutoSave-Plugin#42]
I'm attempting to use this plugin under drupal (using the ckeditor module).
The autosave message appears however when I reload the page I never get the dialog asking to restore the autosaved value.

I tracked this done in the code and the problem is that the object returned by LoadData has a string in the saveTime property and the check in CheckForAutoSavedContent uses this value in a diff call that expects a Date. Replacing:

if (moment(new Date()).diff(autoSavedContentDate, 'minutes') > notOlderThen) {

with

if (moment(new Date()).diff(new Date(autoSavedContentDate), 'minutes') > notOlderThen) {

fixes the problem for me

**Comment by derStephan** [comment]
May I ask, when the patch will be available on http://ckeditor.com/addon/autosave

Or may I ask, what I have to do to implement this into the minified js-files?

Thanks in advance.

**Comment by w8tcha** [comment]
I published version 0.13
