### ISSUE TITLE
how to destroy content on submit

### ISSUE THREAD

**Issue by timtimgit** [w8tcha/CKEditor-AutoSave-Plugin#46]
Hi,

it's a great plugin!

1) what is the meaning and correct use of autosave_SaveKey?
2) I'd like to destroy the stored content when i click the submit button...is it possible?

thanks,
Matteo

**Comment by w8tcha** [comment]
1. that is the id that is used to make sure that the correct stored content is loaded. By default that key is generated based on the 'autosave_' + current url + "_" + editorInstance.id.

But in some cases when you have multiple editors on one page you may want to override that key. But you only need to do that when the wrong content is loaded.

2. Yes you can do that there is a setting for that *config.autosave_saveDetectionSelectors* there you need to enter the id of the submit button.
