### ISSUE TITLE
Disable notification

### ISSUE THREAD

**Issue by ovalek** [w8tcha/CKEditor-AutoSave-Plugin#48]
I find the "saved" notification quite distracting. Can I somehow turn it off?

**Comment by w8tcha** [comment]
No that can not work do you read the readme?

````js
CKEDITOR.editorConfig = function( config ) {
	config.autosave = {messageType : "no"};
};

**Comment by ovalek** [comment]
Oh, sorry. I'm used to that old underscore separator in config. Closing.
