### ISSUE TITLE
Feedback - moving auto-save message to a footer as in GMail

### ISSUE THREAD

**Issue by kryltsov** [w8tcha/CKEditor-AutoSave-Plugin#54]
Great extension - thanks for creating it.

While testing we found that Auto Saved pop-up is often in the way to read what you have just typed. Wouldn't it be nice to move it down below and make as least noticeable as possible?
 
![2016-03-25_205717](https://cloud.githubusercontent.com/assets/102763/14042256/69c0adc2-f2cc-11e5-8a1c-1c34fe2f5d5f.png)

Cheers
Igor

**Comment by johnabela** [comment]
I have been getting soooo many people complaining about this issue. 

Totally agree it needs to get moved.

**Comment by w8tcha** [comment]
I will make an option for that in the next version so you can decide notification message or in the status bar.

Until then you have the option to disable the notifications with config.autosave_disableNotifications = true;
