### ISSUE TITLE
Support for language French Canadian (FR_CA)

### ISSUE THREAD

**Issue by mameawadiop** [w8tcha/CKEditor-AutoSave-Plugin#55]
Used the same file as fr.js and is working.
Also It would be good to have a default language if user's system language is not in the list of the languages autosave support. Otherwise the plugin crashes ckeditor

**Comment by w8tcha** [comment]
> Also It would be good to have a default language if user's system language is not in the list of the languages autosave support. Otherwise the plugin crashes ckeditor

The editor will not crash, the editor will always use the default language and that is english

**Comment by mameawadiop** [comment]
Here is an error I got running a CLE (Sakai 11) that integrated the plugin to the CKEditor.
![error-ckeditor](https://cloud.githubusercontent.com/assets/11739503/14641914/60133e5e-0616-11e6-91f5-8d97e384390f.png)

**Comment by jonespm** [comment]
This looks like an issue with an older version of the plugin 0.11, seems fixed in 0.13. Updating fixed the problem and it looks like it actually does default back to fr, which is nice.

Looks like the fixes were the change from event.editor.lang to editorInstance.lang

Thanks!

**Comment by mameawadiop** [comment]
Thank you,
I will let know the Sakai team.
