### ISSUE TITLE
Feedback: Option for default diffType

### ISSUE THREAD

**Issue by Iramos** [w8tcha/CKEditor-AutoSave-Plugin#58]
Hi There

Is it possible that we can have a config option for default diffType?

Most of my website users have very little to none html knowledge and the sideBySide default view confuse them. Would be nice to be able to set it to default inline.

**Comment by w8tcha** [comment]
I added an option for that in the latest commit for version 0.15

config.autosave = { 
      // The Default Diff Type for the Compare Dialog, you can choose between "sideBySide" or "inline". Default is "sideBySide"
     diffType : "sideBySide"     
};
