### ISSUE TITLE
Conflict with Word Count plug-in

### ISSUE THREAD

**Issue by ncaidin** [w8tcha/CKEditor-AutoSave-Plugin#60]
We have the Word Count plug-in and the AutoSave plug-in installed. When the notification is shown in the status bar (our preference) , the auto save notification overlaps with the word count notification and is unreadable. 
![auto_save_notification_overlap2](https://cloud.githubusercontent.com/assets/5399652/19697408/38464f5a-9ab9-11e6-9518-7c9d885e4541.png)

**Comment by w8tcha** [comment]
In that case the only solution would be to use the notification  bar instead of the status bar, because there is not enough space in the status bar.
