### ISSUE TITLE
Message for importing content should mention that cancel removes autosaved content

### ISSUE THREAD

**Issue by jonespm** [w8tcha/CKEditor-AutoSave-Plugin#64]
The load saved content message says
_"An auto-saved version of this content from "{0}" has been found. Would you like to compare content versions and choose which one to load?'"_

However if you click cancel, the auto saved content is erased completely. It seems like this should be indicated in the message 

_"An auto-saved version of this content from "{0}" has been found. Would you like to compare content versions and choose which one to load? Clicking Cancel will remove previously auto-saved content."_

**Comment by w8tcha** [comment]
Good idea, i updated the english language file
