### ISSUE TITLE
How to configure Save Detection Selectors?

### ISSUE THREAD

**Issue by milossramek** [w8tcha/CKEditor-AutoSave-Plugin#65]
Hi,

our content is created in drupal in collaboration between authors and editors. An author saves the content and changes its state so that an editor can edit it. If the editor sends the content back to the author, the dialog regarding differences in the locally stored and web version is displayed. As I understand the documentation, the option 
saveDetectionSelectors : "a[href^='javascript:__doPostBack'][id*='Save'],a[id*='Cancel']",
should solve this problem.
This, however, does not work for me. 
We use drupal and its ckeditor module, the id of the Save button is 'id="edit-submit"'. So we use 
saveDetectionSelectors : "a[href^='javascript:__doPostBack'][id='edit-submit']]".
This setting is used, I can see it in the "js_conf" section in the html code of the page.

Thank in advance for your help
Milos

**Comment by w8tcha** [comment]
change that to...

`"a[id='edit-submit']]"`
