### ISSUE TITLE
Browser error

### ISSUE THREAD

**Issue by standus** [w8tcha/CKEditor-AutoSave-Plugin#67]
Today I got error on v0.12:
NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached
Line: 225
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by w8tcha** [comment]
In that case you need to inrease the firefox's maxium local storage

In about:config, change "dom.storage.default_quota" to a higher number.

**Comment by standus** [comment]
Its on user side. Please make some condition in your plugin to prevent this error (check size of storage compared with content). And log error to browser console.

**Comment by w8tcha** [comment]
No sorry thats not possible. There is no way to detect the size of the storage or prevent the error and log the error.

**Comment by standus** [comment]
I dont think the same. Search at google: browser storage size detect .
You will see many resources how to detect and compare with content.

**Comment by w8tcha** [comment]
Ok then help me please i find nothing

**Comment by standus** [comment]
In first it must be fixed by try catch, like here:
http://crocodillon.com/blog/always-catch-localstorage-security-and-quota-exceeded-errors
Then you can be inspired by this sources:
https://github.com/marcuswestin/store.js/
https://github.com/zendesk/cross-storage

**Comment by w8tcha** [comment]
okay i added the catch handler
