### ISSUE TITLE
Autosave does not work on Chrome 

### ISSUE THREAD

**Issue by keniobats** [w8tcha/CKEditor-AutoSave-Plugin#72]
Hello,

I've tested autosave plugin on Chrome Version 55.0.2883.95 (64-bit), on macOS Sierra 10.12.12 and every time I reload the editor to see if text was saved, it only saves a chunk of it.

Example:

![screen shot 2017-01-11 at 6 50 10 pm](https://cloud.githubusercontent.com/assets/855242/21867862/e4a0db78-d82e-11e6-8986-0ff58c6a67ac.png)
![screen shot 2017-01-11 at 6 50 24 pm](https://cloud.githubusercontent.com/assets/855242/21867863/e4ae10fe-d82e-11e6-93c2-e1e4366d8fd7.png)

Then I tried it on Safari and it works perfectly so I guess the issue is somehow related to Chrome.

Any hints? Thanks in advance!

**Comment by w8tcha** [comment]
That issue should be fixed with version 0.17

**Comment by keniobats** [comment]
Thanks @w8tcha !
