### ISSUE TITLE
Questions about AutoSave plugin for CKeditor : AutosaveKey ? Autosave delay ? DiffType bug ?

### ISSUE THREAD

**Issue by Lovegiver** [w8tcha/CKEditor-AutoSave-Plugin#73]
Hi @w8tcha ,

I've just downloaded CKeditor including your plugin (v. 0.16) and have some questions for you if you're OK with that.

**1) Autosave and notifications for each keystroke** 

I'm sorry for coming back again on an already opened issue, but I encounter some problems with the plugin and I thought I could find here more infos than on the CK website.

Here what I'm using. My project is a Java one.
```
CKEDITOR.plugins.add("autosave", {
        lang: 'ca,cs,de,en,es,fr,ja,nl,pl,pt-br,ru,sk,sv,zh,zh-cn', // %REMOVE_LINE_CORE%
        requires: 'notification',
        version: **0.16**,
        init: function (editor) {
            // Default Config
            var defaultConfig = {
                **delay: 10**,
                messageType: "notification",
                saveDetectionSelectors: "a[href^='javascript:__doPostBack'][id*='Save'],a[id*='Cancel']",
                saveOnDestroy: false,
                NotOlderThen: 1440,
                **SaveKey: "autosaveKey"**,
                diffType: "sideBySide"
            };
```

The problem is that every keystroke seems to fire an auto-save and that the screen is full of notifications (this issue was reported to you a few days ago) and I'm looking at your code to configure the plugin behaviour.

You're talking about a 25 seconds delay between each auto-save but I cant't find this 25 seconds value anywhere in the code.
Actually, Delay var is set to 10 (seconds ?) but I don't see the difference if I set 100 or 1000.

**2) AutosaveKey** 

I also needed more informations about the "**autosaveKey**" -> what is it ?

Sorry for my poor questions, but I'm an absolute beginner in JS and jQuery and some elements are not clear for me.

**3) DiffType**

When I test the closing and reopening of my browser to verify if my datas have been correctly saved, the window showing historical datas (**difftype**) is **sometimes** broken and I can't see the right part of the table (difftype 'side by side' is selected).

Thanx by advance for your help.

**Comment by w8tcha** [comment]
1. is fixed with version 0.17
2. the autosavekey is the key that is used in the localstorage database for the store the saved data. Its important that the key is unique, Because when you have multiple editors on one page this ensures that the correct data for the correct editor is saved.
3. Please try with version 0.17.
