### ISSUE TITLE
Compatible with 4.7 ckeditor

### ISSUE THREAD

**Issue by Ma3oBblu** [w8tcha/CKEditor-AutoSave-Plugin#82]
Hi! Thanks for plugin! Will be it compatible with 4.7 ckeditor?

**Comment by w8tcha** [comment]
Sure, do you have any issues using the plugin with 4.7?

**Comment by Ma3oBblu** [comment]
we try to set it up with 4.7, but in npm there is no your plugin. on plugin page there are only 4.5, 4.6 compatible versions

**Comment by w8tcha** [comment]
version 0.18 is out now which is now available on the plugins page
