### ISSUE TITLE
Pagespeed minification wonks out compiled LZString

### ISSUE THREAD

**Issue by dhaupin** [w8tcha/CKEditor-AutoSave-Plugin#83]
Pagespeed module screws up LZString when it minifies. There isn't really a way to fix this that I can tell. So perhaps in the readme/documentation here and on CKEditor site, provide a warning + workaround. Thoughts?

Apache:
`ModPagespeedDisallow "*/autosave/js/extensions.min.js*"`

Nginx: 
`pagespeed Disallow "*/autosave/js/extensions.min.js*"`

There should be a wildcard after the ".js" to account for any kind of querystring cachebust in rando platforms.

Thanks for the great plugin.

**Comment by w8tcha** [comment]
Yeah i agree that cannot be fixed from within the plugin. I updated the readme with a warning.

**Comment by dhaupin** [comment]
Sweet, hopefully eliminates future issues (who knows if things like Cloudlflare screw it up too, minifier safe at readme)
