### ISSUE TITLE
Object editor.id is Not Accurate/Consistent Enough for SaveKey

### ISSUE THREAD

**Issue by dhaupin** [w8tcha/CKEditor-AutoSave-Plugin#84]
Editor instance SaveKey string(s) should not be based on init id's, because they are not actually historical id's linked to a specific field. It's based on instance not origin input name. Currently, the default SaveKey uses `editor.id` but that will screw up in a couple of situations:

- When adding a new functionality (such as a new ecom module) which sorts/places any new field in source, changing the count/order.
- When loading editors based on a click into a field to prevent out of memory/stack on pages with hundreds of textareas.

With that in mind, perhaps a better choice for most cases would be using the following for default SaveKey:

`SaveKey: 'autosave_' + window.location + "_" + $('#' + editor.name).attr('name'),`

This looks for the editor field `id`, then pulls the `name` based on that, which in most cases of forms/POST is what is used to submit data. From what i can tell, CK requires a field `id` to load.

I realize none of the default tactics can be 100% accurate due to querystring changes, `id` int/tag/identifier changes, etc, but this seems to link better. Thanks for the sweet plugin.

**Comment by w8tcha** [comment]
Okay makes sense i change the default key

**Comment by dhaupin** [comment]
Thanks man, good work
