### ISSUE TITLE
saveDetectionSelectors not accepting submit buttons?

### ISSUE THREAD

**Issue by rdiamondbww** [w8tcha/CKEditor-AutoSave-Plugin#88]
I've added our 2 submit buttons to the detection selectors and it's not accepting them: 

saveDetectionSelectors : "a[href^='javascript:__doPostBack'][id*='cdh'],a[id*='Cancel'],submit[id*='cdh_buttadminman'],submit[id*='cdh_update_article']",

**Comment by w8tcha** [comment]
an html submit tag does not exist i guess you mean the input button

`<input type="submit" value="Submit">`

in that case use...

`saveDetectionSelectors : "a[href^='javascript:__doPostBack'][id*='cdh'],a[id*='Cancel'],input[id*='cdh_buttadminman'],input[id*='cdh_update_article']",`
