### ISSUE TITLE
Statusbar style alert with textselection plugin

### ISSUE THREAD

**Issue by dhaupin** [w8tcha/CKEditor-AutoSave-Plugin#89]
Its been a minute since ive messed with this, i may be missing something. Is there a reason the autosave message is being forced to popup instead of statusbar when textselection plugin is initialized? Its super annoying to see that popup over your work.

I just tried forcing statusbar message while textselection is enabled, and it seemed to work fine. 

Thanks

**Comment by w8tcha** [comment]
What is the problem, you only need to change the config setting? I prefer the notification message

**Comment by dhaupin** [comment]
You cant change to statusbar alert from config setting if textselection is installed. Its forced set in these 2 places:
https://github.com/w8tcha/CKEditor-AutoSave-Plugin/blob/master/autosave/plugin.js#L49
https://github.com/w8tcha/CKEditor-AutoSave-Plugin/blob/master/autosave/plugin.js#L49

Is/was there a bug or something incompatible with textselection regarding statusbar notifications? Im not seeing any strange behavior unless im missing something.

The reason im asking this is because the notification popup covers content as youre typing, so its highly annoying. With a reduced save delay its even more so.

**Comment by w8tcha** [comment]
Yes sorry the code should be for the wordcount pluging (#69) not for the textselection plugin. I changed the code.

**Comment by dhaupin** [comment]
Niiiice, I was so confused :) Thanks man

**Comment by jonespm** [comment]
I don't think forcing this is the appropriate setting/resolution for #60. Now if someone has the wordcount it can't be set to "no" to turn it off, and can't set it to statusbar even if there might have be enough space. Seems better to me just revert the change made for this rather than to force the preference.
