### ISSUE TITLE
Autosave plugin fails to start when editor name contains a colon.

### ISSUE THREAD

**Issue by buckett** [w8tcha/CKEditor-AutoSave-Plugin#90]
In the web application Sakai we use jQuery and jQuery-migrate and when we attempt to create a ckeditor instance out of a textarea that has a name containing a colon we get an error because the search is invalid.

Escaping the name before doing the search is one way to fix this issue. Another is just to do a `document.getElementById()` instead of using jQuery.

You can see more about the issue on: https://jira.sakaiproject.org/browse/SAK-33307

**Comment by jonespm** [comment]
It looks like this was caused just recently by #87

**Comment by w8tcha** [comment]
fixed with 45eb7ee073eb1743395f27fd065a027c90770bb1
