### ISSUE TITLE
Compatible

### ISSUE THREAD

**Issue by yedajiang44** [w8tcha/CKEditor-AutoSave-Plugin#96]
Hello~ Here I come again

This plugin is not compatible with  [Upload File](https://ckeditor.com/cke4/addon/uploadfile),After "autosave" is enabled, "UploadFile" fails, and I think it may be related to "JQuery" dependency

-------------------------------------------------------------------------------------------

The above comes from the computer translation, including this sentence and the latter sentence, Because my English is very poor

**Comment by w8tcha** [comment]
Does it work without the autosave plugin? Are you getting any java script errors in the browser console?

**Comment by yedajiang44** [comment]
autosave plugin is work , but  Upload File don't work , and console no any message , my app is asp mvc  ,I always  think it may be related to "JQuery" dependency

**Comment by w8tcha** [comment]
but does the upload file plugin works without the autosave plugin?

**Comment by yedajiang44** [comment]
Please click the url [I recorded GIF](http://112.25.218.20:8000/f/60f9083462/)（You can download it because the preview is not clear）

**Comment by w8tcha** [comment]
Sorry but the link doesn't work. You can attach that file direct in here

**Comment by w8tcha** [comment]
can you post your config file with both autosave and uploadfile plugin enabled?

**Comment by yedajiang44** [comment]
![Uploading 123.gif…]()

**Comment by yedajiang44** [comment]
[http://www.mediafire.com/file/i1mf3ebku0vm71l/123.gif](http://www.mediafire.com/file/i1mf3ebku0vm71l/123.gif)
My God, finally uploaded（GitHub always error）, and fuck the China's network environment

**Comment by w8tcha** [comment]
can you post your config file with both autosave and uploadfile plugin enabled?

You can paste the content as text here

**Comment by yedajiang44** [comment]
CKEDITOR.editorConfig = function (config) {
    // Define changes to default configuration here. For example:
    // config.language = 'fr';
    // config.uiColor = '#AADC6E';
    config.image_previewText = " ";
    config.extraPlugins = 'uploadfile';
    config.extraPlugins = 'uploadimage';
    // 上传图片路径
    config.uploadUrl = "/Files/UploadFile";



    // 工具栏（基础'Basic'、全能'Full'、自定义）plugins/toolbar/plugin.js
    config.toolbar = 'Full';
    //启动自动保存插件
    config.extraPlugins = 'autosave';
    
    //自动保存插件配置
    config.autosave = {
        // Auto save Key - The Default autosavekey can be overridden from the config ...
        Savekey: 'autosave_' + window.location + "_" + $('#' + CKEDITOR.editor.name).attr('name'),

        //保存的时间（默认为1440，一天）后自动保存的内容被忽略
        NotOlderThen: 1440,

        // 当销毁时保存-设置当编辑销毁时保存内容（默认为false）
        saveOnDestroy: false,

        // 设置保存按钮通知插件时，内容是由用户保存，不需要存储临时。
        saveDetectionSelectors: "a[href^='javascript:__doPostBack'][id*='Save'],a[id*='Cancel']",

        // 通知类型-如果您想显示“Auto Saved”消息，如果是，您可以显示为状态栏中的Notification或Message（默认是“notification”）
        messageType: "notification",

        // 在状态栏显示
        //messageType : "statusbar",

        // Show no Message
        //messageType : "no",

        // 自动保存间隔（内容有变化时才保存）
        delay: 5,

        // 对于比较对话框的默认类型，你可以选择“sidebyside”或“inline”。默认是“sidebyside”
        diffType: "sideBySide",

        // 加载时使它直接加载保存的内容
        autoLoad: true
    };

};

**Comment by yedajiang44** [comment]
`
CKEDITOR.editorConfig = function (config) {
    // Define changes to default configuration here. For example:
    // config.language = 'fr';
    // config.uiColor = '#AADC6E';
    config.image_previewText = " ";
    config.extraPlugins = 'uploadfile';
    config.extraPlugins = 'uploadimage';
    // 上传图片路径
    config.uploadUrl = "/Files/UploadFile";



    // 工具栏（基础'Basic'、全能'Full'、自定义）plugins/toolbar/plugin.js
    config.toolbar = 'Full';
    //启动自动保存插件
    config.extraPlugins = 'autosave';
    
    //自动保存插件配置
    config.autosave = {
        // Auto save Key - The Default autosavekey can be overridden from the config ...
        Savekey: 'autosave_' + window.location + "_" + $('#' + CKEDITOR.editor.name).attr('name'),

        //保存的时间（默认为1440，一天）后自动保存的内容被忽略
        NotOlderThen: 1440,

        // 当销毁时保存-设置当编辑销毁时保存内容（默认为false）
        saveOnDestroy: false,

        // 设置保存按钮通知插件时，内容是由用户保存，不需要存储临时。
        saveDetectionSelectors: "a[href^='javascript:__doPostBack'][id*='Save'],a[id*='Cancel']",

        // 通知类型-如果您想显示“Auto Saved”消息，如果是，您可以显示为状态栏中的Notification或Message（默认是“notification”）
        messageType: "notification",

        // 在状态栏显示
        //messageType : "statusbar",

        // Show no Message
        //messageType : "no",

        // 自动保存间隔（内容有变化时才保存）
        delay: 5,

        // 对于比较对话框的默认类型，你可以选择“sidebyside”或“inline”。默认是“sidebyside”
        diffType: "sideBySide",

        // 加载时使它直接加载保存的内容
        autoLoad: true
    };

};`

**Comment by w8tcha** [comment]
okay that can not work, you need to define the extra plugins in one line

````js

  config.extraPlugins = 'uploadfile,uploadimageautosave';
````

**Comment by yedajiang44** [comment]
God。。。。thank you very much！！ 
But in JavaScript, how to clear the saved data , like after submitting the form

**Comment by w8tcha** [comment]
> But in JavaScript, how to clear the saved data , like after submitting the form

For that is the config setting

````js

  saveDetectionSelectors: "a[href^='javascript:__doPostBack'][id*='Save'],a[id*='Cancel']",
````

in the examples the submit form is called via a submit Button which is an a html tag containing the id Save or Cancel

**Comment by yedajiang44** [comment]
All solved! Thanks very much！
