### ISSUE TITLE
Remove jQuery dependency completely

### ISSUE THREAD

**Issue by crisp-tweakers** [w8tcha/CKEditor-AutoSave-Plugin#97]
I just noticed that there is still one dependency on jQuery in this plugin. When removing this the loading of the complete jQuery library in the 'instanceReady' event in plugin.js will become obsolete which decreases the total footprint of this plugin and increases performance. The dependency is in plugin.js on lines 91-93:
`jQuery(config.saveDetectionSelectors).click(function() {
    RemoveStorage(config.SaveKey, editorInstance);
});`
this can easiliy be replaced with something like:
`CKEDITOR.tools.array.forEach(
    CKEDITOR.document.find(config.saveDetectionSelectors).toArray(),
    function(el) {
        el.on('click', function() {
            RemoveStorage(config.SaveKey, editorInstance);
        });
    }
);`

**Comment by w8tcha** [comment]
Can you send in a pull request with the changes?

**Comment by w8tcha** [comment]
thanks there was one more usage of jquery, now its completely removed
